/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Arrays;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void rollTest() {
        Library sut = new Library();
        System.out.println("Dice rolls: " + Arrays.toString(sut.roll(6)));
    }
    @Test void duplicateTest() {
        Library sut = new Library();
        int[] array = {2,4,6,2};
        assertTrue(sut.containsDuplicates(array),"True or false?");
    }
}
