/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Random;
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    // Rolling Dice
    public int[] roll(int n) {
        Random rand = new Random();
        int[] diceRoll = new int[n];
        for (int i = 0; i < n; i++) {
            int randNum = rand.nextInt(6);
            diceRoll[i] = randNum + 1;
        }
        return diceRoll;
    }

    // Contains Duplicates
    public boolean containsDuplicates(int[] array) {
        for (int i = 0; i < array.length; i++) {
            for (int j = 1; j < array.length; j++) {
                if (i == j) continue;
                if (array[i] == array[j])
                    return true;
            }
        }
        return false;
    }

    // Calculating Averages



}