/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void testRestaurantName() {
        Restaurant newRestaurant = new Restaurant("Maza Grill", "$$", 4);
        // Do not know what to act
        assertSame("Maza Grill", "$$", 4);
    }
    @Test void testReview() {
        Review newReview = new Review("Sharmarke", "Good halal spot", 4);
        // Do not know what to act
        assertSame("Maza Grill", "$$", 4);

    }

    }
