/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void testingAddReviewOnRestaurant(){
        // Arrange
        Review testReview = new Review("Good hala spot", "Sharmarke", 4);
        Restaurant testRestaurant = new Restaurant("Maza Grill", "$$");
        // Act
        testRestaurant.addReview(testReview);
        // Assert
        assertTrue(testRestaurant.getReviews().contains(testReview));
        assertFalse(testRestaurant.getReviews().isEmpty());
        assertEquals(testReview.getNumOfStars(), testRestaurant.getNumOfStars());
    }

    // Constructor tests
    @Test void testingReviewConstructor(){
        // Arrange
        // Act
        Review testReview = new Review("Body", "Author", 5);
        // Assert
        assertEquals("Body", testReview.getText());
        assertEquals("Author", testReview.getAuthor());
        assertEquals(5, testReview.getNumOfStars());
    }
}
